### ISSUE TITLE
Location of .lede : base or trumps layer ?

### ISSUE THREAD

**Issue by florianbouvot** [inuitcss/base.paragraphs#1]
Since separation of headings in base and trumps layers, I wonder if `.lede` is in the right place?

1) `.lede` is an exception and must stay in base layer
2) `.lede` must move to trumps layer. To go further, we might consider a general utility for text sizes?

**Comment by nenadjelovac** [comment]
I think 2) plus it needs to have `.u-` prefix.

**Comment by florianbouvot** [comment]
@nenadjelovac course with the prefix

**Comment by florianbouvot** [comment]
@nenadjelovac And what's your opinion about a general trump for text sizes (lede, small print and why not headings)?

**Comment by nenadjelovac** [comment]
@florianbouvot headings already exists in trumps. More about my opinion about it [here](https://github.com/inuitcss/base.headings/issues/4) :)

There are font sizes/weights that could be added as well, and so on and so on.

**Comment by csswizardry** [comment]
Yeah, you’re right, this needs promoting into the Trumps layer :)

**Comment by florianbouvot** [comment]
ping

**Comment by csshugs** [comment]
Can we do this? I mean, we'd have to rename the repo 😬 . It's dangerous, right?

**Comment by florianbouvot** [comment]
I think this module is not needed, we don't need to port it in the new version.

**Comment by csshugs** [comment]
So closing this then?

**Comment by csshugs** [comment]
@inuitcss/core Since this is a bug, I'd like to fix this (even if it's pre-alpha).

Does anyone know if it will break availability (for bower/npm) when we rename the repo name to ”trumps.paragraphs”? Will a `bower install inuit-paragraphs`/`npm install inuit-paragraphs` still work?

**Comment by csshugs** [comment]
Since this repository is now officially deprecated, I close this.
